### ISSUE TITLE
可用谢谢

### ISSUE THREAD

**Issue by helaobibi** [CharlesPikachu/Music-Downloader#2]
可用，但是请问可不可以下载无损版的文件，谢谢

**Comment by CharlesPikachu** [comment]
这个脚本不支持下载flac文件。
可以尝试使用百度的API来下载flac文件：
http://music.baidu.com/data/music/fmlink

**Comment by CharlesPikachu** [comment]
现在已经支持下载无损音乐了，但只有百度的，资源较少，后续会尝试进行扩展
