### ISSUE TITLE
虾米音乐获取播放链接失败了

### ISSUE THREAD

**Issue by t880216t** [CharlesPikachu/Music-Downloader#3]
例子：
https://www.xiami.com/song/playlist/id/1796001263/object_name/default/object_id/0/cat/json
这个获取播放链接的请求现在是跳登录页面，无法获取播放链接

**Comment by CharlesPikachu** [comment]
似乎只是部分歌曲无法获取。。。我不怎么用虾米，有时间我再看看。

**Comment by CharlesPikachu** [comment]
现在已经重新支持虾米音乐了
